### PR TITLE
Please review my codes

### PR DESCRIPTION
**Pull request by makomination**
Have you reviewed my codes?
It doesn't seem to get any review by anyone.
Also, I met all requirement.

### CODE REVIEW

**Comment by yingmu52** [comment]
We reviewed your code, unfortunately, we will need further consideration.
- When first received your code, it is not straightforward to test. 
- The project lacks a proper scheme and we fail to compile the code because there were some typos. 
- There is no instruction to as to how to properly configure your code. 
- In the requirement, I specifically asked `DO NO SUBMIT A PULL REQUEST`. 

We are not only looking for coding skill but also team collaboration, communications skills, and the consistency and inheritability of your work. There are better candidates in our list that finished this test with better execution and better documentation. Unfortunately, we will not move forward this point. Thanks for your interests.

**Comment by makomination** [comment]
I closed the request right now. 
I just wanted to make sure if you saw my codes.
(I didn't know your contact)

I doubted if you reviewed my codes because DB records didn't change at all(If you'd tested it, it must've changed) and there was no mail about screening test from you so far.

It's weird because in my environment it works correctly.
In the beginning, in my environment,  the app on your commit didn't work, so I changed some app info.

To be sure, It might be more kind if I'd changed it back for your environment and added some notes.
I understood you judged there was a better candidate.
However, I regretted because each function in my app works perfectly...

Thanks for your feed back.
Then, I can go ahead.

**Comment by yingmu52** [comment]
@makomination as I mentioned before, at the time we received your code, it wasn't functional. I had to adjust a few things before I can compile. also, I made the firebase DB point for my working project. This is something we debate about on daily basis. We as software developers can not assume that our product builds fine in our client's environment. When it fails, you not only lost your product reputation but also your customers. The same principle applies. 

Thanks for your work.

**Comment by makomination** [comment]
@yingmu52 
>This is something we debate about on daily basis. We as software developers can not assume that our product builds fine in our client's environment. When it fails, you not only lost your product reputation but also your customers.

Thanks for the nice advice. I'll care that in the future.

>Also, In an open source project, when a pull request is opened. it can be seen even when it is closed, that means this repo will soon be deprecated, as our future applicant will be able to find the reference to an answer here in the pull request list. This caused some inconvenience for us.

Sorry about that, but you can see other's codes from the folk list, so if you want to hide your recruiting process, you must use private repo and invite applicants to it.

**Comment by yingmu52** [comment]
> so if you want to hide your recruiting process, you must use private repo and invite applicants to it.

If we invite the applicants to a private repo, would it stop them from seeing the folk list and pull request? 

`Actually`, I kind of like the discussion here. 
So, if you don't mind. What makes you stand out the best? If I were to give you a second chance. How would you convince us to hire you?

**Comment by yingmu52** [comment]
Here is some evidence. 
In `AppDelegate.swift`, line `23`, it should be `FIRApp.configure()` not `FirebaseApp.configure()`

**Comment by makomination** [comment]
>If we invite the applicants to a private repo, would it stop them from seeing the folk list and pull request?

You can create some private repos(as the same project) for each applicant, then you can manage applicant's codes individually.

>Here is some evidence.
In AppDelegate.swift, line 23, it should be FIRApp.configure() not FirebaseApp.configure()

Please go to see https://firebase.google.com/docs/ios/setup. In the bottom of codes, please choose "Swift". It says we should use FirebaseApp.configure() in Swift.

**Comment by yingmu52** [comment]
> You can create some private repos(as the same project) for each applicant, then you can manage applicant's codes individually.

How do I prevent one from seeing other applicants code

> Please go to see https://firebase.google.com/docs/ios/setup. In the bottom of codes, please choose "Swift". It says we should use FirebaseApp.configure() in Swift.

The reason is `use_frameworks!` is for swift pod, in your pod file, 
```
pod 'Firebase/Core'
pod 'Firebase/Database'
```
is place in a way for objective-c, although you set up as a swift project. but the actual API is from Objective-C. If you take a look at the Google documentation for obj-c code, it is `[FIRApp configure];`, this is why your code has errors on our side.

**Comment by makomination** [comment]
>How do I prevent one from seeing other applicants code
For example, you can create private repositories like VDMChat1, VDMChat2 and VDMChat3 for 3 applicants.They are different names,  but same projects (use git clone).

I don't understand the pod file perfectly, but I think in Swift project, we also need 
>pod 'Firebase/Core'
pod 'Firebase/Database'.
I think the pod file seems a ruby file, so it doesn't matter the format, maybe (excluding the code 'use_frameworks!').

**Comment by yingmu52** [comment]
> For example, you can create private repositories like VDMChat1, VDMChat2 and VDMChat3 for 3 applicants.They are different names, but same projects (use git clone).

This is a not an elegant solution. I am pretty busy every day, managing that many repos will not be a pleasant thing to do. Imagine you have 10 applicants every week. Everybody is asking for a review and stuff. that will be very out of control. 

> I don't understand the pod file perfectly, but I think in Swift project, we also need

You are not the only one who makes this mistake, out of that many applicants, only a few figured it out and we hired one who delivers it within 4 hours. and it runs perfectly. We hired him right away.

**Comment by makomination** [comment]
>This is a not an elegant solution. I am pretty busy every day, managing that many repos will not be a pleasant thing to do. Imagine you have 10 applicants every week. Everybody is asking for a review and stuff. that will be very out of control.

OK, it's up to you. It's just a tradeoff and depends on whether you want to keep your recruiting process secret or to open all codes for all applicants but manage relatively easily. I don't think it's tough to manage because you need just type "git clone", though. Also, You can search for your repository by using a search bar even if you have a lot of projects.

>You are not the only one who makes this mistake, out of that many applicants, only a few figured it out and we hired one who delivers it within 4 hours. and it runs perfectly. We hired him right away.

It's resonable.

**Comment by makomination** [comment]
I recommend you to create another account for only recruiting purpose.

**Comment by yingmu52** [comment]
@makomination Thanks for you advice, if you wish, please remove your fork repo, good luck

**Pull request closed without merging**
